language: csharp
solution: travis-ci-hello-world-c-sharp-test.sln
script:
  - xbuild /p:Configuration=Release travis-ci-hello-world-c-sharp-test.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MyPoject.Tests/bin/Release/travis-ci-hello-world-c-sharp-test.dll